# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: ArtifactoryGradle@1
  inputs:
    gradleBuildFile: 'build.gradle'
    options: '-d'
    tasks: 'artifactoryPublish'
    artifactoryResolverService: 'gradlesc'
    sourceRepo: 'gradle-gradle-release'
    artifactoryDeployerService: 'gradlesc'
    targetRepo: 'gradle-gradle-dev-local'
